In [1]:
import panda as p 
csv_df = pd.read_csv('cars.csv')
csv_df.head()

ModuleNotFoundError: No module named 'pandas'

# NumPy Overview
1. Arrays
2. array shaping and transposition
3. Array broadcasting
4. idk
5. girl moves too quick

# Arrays 
Structured list of numbers 
* Vectors
* Matrices
* Images
* Tensors
* ConvNets

In [2]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]], dtype = np.float32)
print(a.ndim, a.shape, a.dtype)

2 (2, 3) float32


In [9]:
#array excercise 
#1 
b = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(b)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [13]:
#Shaping 
a = np.array([1,2,3,4,5,6]) 
a = a.reshape(3,2) 
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
 a = a.reshape (2, -1) 
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a = a.ravel()
a

array([1, 2, 3, 4, 5, 6])

In [17]:
#Transposition 
a = np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [18]:
a = a.T
a

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [23]:
a = a.transpose((1,0))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])